version: "3"
services:
  db:
    image: postgres:alpine
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=flask_api
    ports:
    - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      - DB_PASSWORD=root
      - DB_USER=root
      - DB_DATABASE=flask_api
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    command: sh -c "flask run --host=0.0.0.0 --port=5000"

volumes:
  db:
    driver: local